### PR TITLE
update nativescript-orientation to 2.2.0

### PR DESCRIPTION
**Pull request by AsrarMemon**

### CODE REVIEW

**Comment by alexandruantonica** [comment]
@toddanglin Is there any problem with this PR ?

**Comment by toddanglin** [comment]
Thanks for submitting the PR! Will merge today and publish new version to NPM.

**Comment by AsrarMemon** [comment]
can you please merge this because i face error which is mention below  
``` page._refreshCss is not a function  ```

as per nativescript-orientation plugin they solve this issues in 2.0.1 version so we have to update version in your dependencies

**Comment by toddanglin** [comment]
Yep. Working on it now.

As I worked on merging this and getting the plugin updated for the latest version of {N}, it uncovered a few other problems that needed to be addressed. I think I've got them all covered now, so assuming everything checks-out in the demo apps, I'll publish the update shortly.

As a reminder, you can always build against your own local copy of this plugin if you're blocked. Just clone the plugin, make your changes, and then update your app's `package.json` to point to the local directory that contains your copy of the plugin (i.e. `file://../nativescript-trace-raven`). Not ideal, obviously, but helpful if you get blocked and are able to make a quick change to fix a plugin for yourself.

**Comment by toddanglin** [comment]
Okay. I manually updated the plugin to include the latest versions of these plugins and pushed the update to NPM (v1.1.1). Let me know if you have any trouble. Thanks again for helping push this plugin forward!

**Pull request closed without merging**
